apiVersion: v1
kind: ConfigMap
metadata:
  name: finconecta-config
  namespace: finconecta
data:
  # Para Docker Desktop, usamos servicios por nombre
  db-host: "postgres-service.finconecta.svc.cluster.local"
  db-port: "5432"
  db-name: "finconecta"
  app-context-path: "/finconecta"
  backend-url: "http://backend-service.finconecta.svc.cluster.local:8080"