apiVersion: v1
kind: Secret
metadata:
  name: finconecta-secrets
  namespace: finconecta
type: Opaque
stringData:
  postgres-password: "postgres"
  jwt-secret: "miClaveSecretaSuperSeguraParaJWT2024Finconecta1234567890"