version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: postgres-windows
    restart: unless-stopped
    ports:
      - "5432:5432"

    environment:
      POSTGRES_HOST_AUTH_METHOD: md5
      POSTGRES_DB: finconecta
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_INITDB_ARGS: >
        --encoding=UTF-8  --lc-collate=C  --lc-ctype=C  --auth-host=md5  --auth-local=md5
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./init-scripts:/docker-entrypoint-initdb.d:ro
    command: >
      postgres  -c listen_addresses='*' -c port=5432 -c log_statement=all -c log_connections=on -c log_disconnections=on
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d finconecta" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

volumes:
  postgres-data:
    driver: local
